# Generated by Django 4.0.3 on 2022-03-20 14:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='expenses',
            old_name='caterogy',
            new_name='category',
        ),
    ]
